### ISSUE TITLE
Add Custom Server Side Validation.

### ISSUE THREAD

**Issue by chrisjamiecarter** [chrisjamiecarter/habit-tracker-mvc#29]
You can add custom server side validation to your model. You can find an example here: https://stackoverflow.com/questions/71043332/how-and-where-to-validate-uniqueness-of-attribute-property-in-asp-net-core-mvc-u
image

**Comment by Pantex9** [comment]
Hi, i am interested in resolving this issue.

**Comment by chrisjamiecarter** [comment]
@Pantex9 

Sure fork, resolve, and submit a pull request.

The custom server side validation needs to be applied to the category name check to ensure no duplicates are added.

I would also like to confirm that the database has a unique index on the field.

Let me know if you need anymore information.

**Comment by chrisjamiecarter** [comment]
git fetch origin
git checkout feature-29-add-custom-server-side-validation

**Comment by Pantex9** [comment]
Okay, thanks

**Comment by Pantex9** [comment]
Hi, what do you mean by category, is it a habit or what? (I don't see a category model on the project)
Which parameter you want to be unique, Name?

**Comment by chrisjamiecarter** [comment]
@Pantex9 
Sorry I should have been more specific.

Habit -> Name


The current implementation is in the CreateHabitModel OnPost method.

**Comment by Pantex9** [comment]
Thanks.
I need one more clarification, what do you mean by "I would also like to confirm that the database has a unique index on the field.". when you want to confirm, in code or?

**Comment by chrisjamiecarter** [comment]
@Pantex9,

Check the TableQueries.cs file.

There should be a CreateHabitTable query. I would like to add a Unique Index on the Name column as a backup.

So we would have Client Side Validation, Server Side Validation and then Database Validation too.

**Comment by Pantex9** [comment]
Hi, i can't push my changes on branch feature-29-add-custom-server-side-validation.

**Comment by chrisjamiecarter** [comment]
@Pantex9, No I think you will need to fork the repo, make your changes, and then pull request:

https://medium.com/swlh/forks-and-pull-requests-how-to-contribute-to-github-repos-8843fac34ce8

**Comment by chrisjamiecarter** [comment]
Hey @Pantex9,

QQ as I am curious,

How did you find this repository/issue to work on?

**Comment by Pantex9** [comment]
For a university assignment, I looked for a GitHub repository or project with open issues that need to be resolved. I searched on GitHub with filters for open issues and c# language. also ordered by date and find this interesting issue.

**Comment by chrisjamiecarter** [comment]
That is awesome!
